# Generated by Django 4.2.17 on 2025-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
