# Generated by Django 4.2.17 on 2025-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
