# Generated by Django 4.2.17 on 2025-01-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField(default='Now')),
            ],
        ),
    ]
