# Generated by Django 4.2.17 on 2025-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0009_alter_buyer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
