# Generated by Django 4.2.17 on 2025-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0010_promo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
