# Generated by Django 4.2.17 on 2025-01-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
